# Change baseurl before deploy
baseurl = "https://MyNameMyLastName.org/blog"
languageCode = "en-us"
paginate = 5
title = "MyName's Blog"
copyright = "myname"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "en"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = false

# Change it to your Disqus shortname before using
disqusShortname = "MyNameMyLastName-org"
googleAnalytics = "GoogleAnalyticsID"

contentDir = "content/blog"
publishDir = "public/blog"
staticDir = "static/blog"

enableRobotsTXT = true
enableGitInfo = true

[FrontMatter]
date = [ "date", "publishDate", "lastmod" ]
lastmod = [ "lastmod", ":git", "date", "publishDate" ]
publishDate = [ "publishDate", "date" ]
expiryDate = [ "expiryDate" ]